name: Check types
on:
  pull_request_target:
    branches:
      - main
    paths:
      - "**.tsx?"
jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2

      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"
      - run: yarn --frozen-lockfile
      - run: yarn type-check
